spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud-personaBackend
    username: postgres
    password: Csr73203440**
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
